// generated by gen-validator -model=User; DO NOT EDIT

package models

import "github.com/bluele/gen-validator/libs"

func (obj *User) Validate() []error {
	var err error
	var errors []error

	err = libs.Min(obj.Name, "3")
	if err != nil {
		errors = append(errors, err)
	}
	err = libs.Max(obj.Name, "12")
	if err != nil {
		errors = append(errors, obj.ErrorMaxName())
	}
	err = libs.Min(obj.Age, "18")
	if err != nil {
		errors = append(errors, obj.ErrorMinAge())
	}

	return errors
}
